# Project Name
TARGET = V.oscillator

# Sources
CPP_SOURCES = V.oscillator_main.cpp voscillator.cpp UIvosc.cpp

# Library Locations
LIBDAISY_DIR = ../../libdaisy
DAISYSP_DIR = ../../DaisySP

# Core location, and generic Makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile
